/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as DonateIndexRouteImport } from './routes/donate.index'
import { Route as AcademyIndexRouteImport } from './routes/academy.index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as AcademySlugRouteImport } from './routes/academy.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateIndexRoute = DonateIndexRouteImport.update({
  id: '/donate/',
  path: '/donate/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyIndexRoute = AcademyIndexRouteImport.update({
  id: '/academy/',
  path: '/academy/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademySlugRoute = AcademySlugRouteImport.update({
  id: '/academy/$slug',
  path: '/academy/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy/$slug': typeof AcademySlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/academy/': typeof AcademyIndexRoute
  '/donate/': typeof DonateIndexRoute
  '/events/': typeof EventsIndexRoute
  '/news/': typeof NewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academy/$slug': typeof AcademySlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/academy': typeof AcademyIndexRoute
  '/donate': typeof DonateIndexRoute
  '/events': typeof EventsIndexRoute
  '/news': typeof NewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academy/$slug': typeof AcademySlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/academy/': typeof AcademyIndexRoute
  '/donate/': typeof DonateIndexRoute
  '/events/': typeof EventsIndexRoute
  '/news/': typeof NewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academy/$slug'
    | '/events/$slug'
    | '/news/$slug'
    | '/academy/'
    | '/donate/'
    | '/events/'
    | '/news/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academy/$slug'
    | '/events/$slug'
    | '/news/$slug'
    | '/academy'
    | '/donate'
    | '/events'
    | '/news'
  id:
    | '__root__'
    | '/'
    | '/academy/$slug'
    | '/events/$slug'
    | '/news/$slug'
    | '/academy/'
    | '/donate/'
    | '/events/'
    | '/news/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademySlugRoute: typeof AcademySlugRoute
  EventsSlugRoute: typeof EventsSlugRoute
  NewsSlugRoute: typeof NewsSlugRoute
  AcademyIndexRoute: typeof AcademyIndexRoute
  DonateIndexRoute: typeof DonateIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate/': {
      id: '/donate/'
      path: '/donate'
      fullPath: '/donate/'
      preLoaderRoute: typeof DonateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/': {
      id: '/academy/'
      path: '/academy'
      fullPath: '/academy/'
      preLoaderRoute: typeof AcademyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/$slug': {
      id: '/academy/$slug'
      path: '/academy/$slug'
      fullPath: '/academy/$slug'
      preLoaderRoute: typeof AcademySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademySlugRoute: AcademySlugRoute,
  EventsSlugRoute: EventsSlugRoute,
  NewsSlugRoute: NewsSlugRoute,
  AcademyIndexRoute: AcademyIndexRoute,
  DonateIndexRoute: DonateIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
