
-- News articles
INSERT INTO public.news (slug, title, excerpt, body, source, published, published_at) VALUES
('mobilisation-nationale-paix', 
  '{"en":"National Day of Peaceful Mobilization","fr":"Journée nationale de mobilisation pacifique","mg":"Andro nasionalin''ny hetsika am-pilaminana"}'::jsonb,
  '{"en":"Cells from 22 cities coordinate a synchronized peaceful action focused on transparency and youth representation.","fr":"Les cellules de 22 villes coordonnent une action pacifique synchronisée axée sur la transparence et la représentation des jeunes.","mg":"Mandrindra hetsika am-pilaminana miaraka avy amin''ny tanàna 22 ny solontena tanora momba ny mangarahara."}'::jsonb,
  '{"en":"# A Movement, Not a Moment\n\nOn the chosen date, GEN Z cells across the country will hold synchronized assemblies. Each gathering follows the **non-violence charter**: no weapons, no provocations, no property damage. Marshals trained in de-escalation will be visible at every site.\n\n## Three Demands\n1. Public budget transparency portal\n2. Youth seats in regional consultative councils\n3. Independent oversight of public procurement\n\n## How to Participate Safely\n- Memorize the legal hotline\n- Travel in groups of 3 minimum\n- Bring water, ID, and a fully charged phone\n- Leave biometric unlock disabled","fr":"# Un mouvement, pas un instant\n\nÀ la date choisie, les cellules GEN Z à travers le pays tiendront des assemblées synchronisées. Chaque rassemblement suit la **charte de non-violence** : aucune arme, aucune provocation, aucun dégât matériel. Des marshals formés à la désescalade seront visibles sur chaque site.\n\n## Trois revendications\n1. Portail public de transparence budgétaire\n2. Sièges jeunes dans les conseils consultatifs régionaux\n3. Contrôle indépendant des marchés publics\n\n## Comment participer en toute sécurité\n- Mémorisez la hotline juridique\n- Déplacez-vous en groupe de 3 minimum\n- Apportez de l''eau, une pièce d''identité, un téléphone chargé\n- Désactivez le déverrouillage biométrique","mg":"# Hetsika maharitra, fa tsy fotoana fohy\n\nAmin''ny daty voafidy, ny solontena GEN Z manerana ny firenena dia hanao fivoriana miaraka. Ny fihaonana tsirairay dia manaraka ny **sata fanoherana herisetra**: tsy misy fitaovam-piadiana, tsy misy fanaitairana, tsy misy fanimbana.\n\n## Fitakiana telo\n1. Portail mangarahara momba ny tetibola\n2. Toerana ho an''ny tanora ao amin''ny filankevitra mpanolo-tsaina isam-paritra\n3. Fanaraha-maso mahaleo tena ny tsenan''ny Fanjakana\n\n## Ahoana no fomba fandraisana anjara mandry fahalemana\n- Tadidio ny laharana fanampiana ara-dalàna\n- Mivoaka miaraka amin''ny olona telo farafahakeliny\n- Mitondrà rano, kara-panondro, sy finday voakaroka\n- Vonoy ny fanokafana biometrika"}'::jsonb,
  'manual', true, now() - interval '1 day')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.news (slug, title, excerpt, body, source, published, published_at) VALUES
('transparence-financiere-mouvement',
  '{"en":"Financial Transparency Report Q1","fr":"Rapport de transparence financière T1","mg":"Tatitra mangarahara momba ny vola Q1"}'::jsonb,
  '{"en":"Every ariary received and spent is now publicly listed. Read the full breakdown of donations, allocations, and reserves.","fr":"Chaque ariary reçu et dépensé est désormais publiquement listé. Consultez le détail complet des dons, allocations et réserves.","mg":"Ny ariary tsirairay azo sy lany dia voasoratra ampahibemaso. Vakio ny tatitra feno momba ny fanomezana sy ny fizarana."}'::jsonb,
  '{"en":"# Transparency is a Habit, Not a Slogan\n\nThis quarter the movement received **84,200,000 MGA** in citizen donations. Here is how it was used:\n\n- 38% — Legal aid fund (4 cases supported)\n- 24% — Field medic kits (210 kits distributed)\n- 18% — Training materials and translations\n- 12% — Communication infrastructure (servers, secure channels)\n- 8% — Operational reserve\n\nNo individual receives a salary. All organizers are volunteers. Receipts are archived and auditable.","fr":"# La transparence est une habitude, pas un slogan\n\nCe trimestre, le mouvement a reçu **84 200 000 MGA** en dons citoyens. Voici l''utilisation :\n\n- 38 % — Fonds d''aide juridique (4 dossiers soutenus)\n- 24 % — Kits médic de terrain (210 kits distribués)\n- 18 % — Matériel de formation et traductions\n- 12 % — Infrastructure de communication\n- 8 % — Réserve opérationnelle\n\nAucun individu ne reçoit de salaire. Tous les organisateurs sont bénévoles.","mg":"# Ny mangarahara dia fahazarana, fa tsy teny sahaza\n\nTamin''ity telovolana ity dia nahazo **84 200 000 MGA** ny hetsika. Ity ny fampiasana:\n\n- 38% — Tahirim-bola fanampiana ara-dalàna\n- 24% — Fitaovana medic eny an-toerana (kit 210)\n- 18% — Fitaovana fiofanana sy fandikan-teny\n- 12% — Fotodrafitr''asa serasera\n- 8% — Tahiry fiasana\n\nTsy misy mahazo karama. Mpilatsaka an-tsitrapo avokoa ny mpandrindra."}'::jsonb,
  'manual', true, now() - interval '3 days')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.news (slug, title, excerpt, body, source, published, published_at) VALUES
('partenariat-medic-croix',
  '{"en":"Medical Partnership Expands to 6 Cities","fr":"Le partenariat médic s''étend à 6 villes","mg":"Mihitatra amin''ny tanàna 6 ny fiaraha-miasa medic"}'::jsonb,
  '{"en":"Volunteer first responders now cover Antananarivo, Toamasina, Antsirabe, Mahajanga, Fianarantsoa and Toliara.","fr":"Les secouristes bénévoles couvrent désormais Antananarivo, Toamasina, Antsirabe, Mahajanga, Fianarantsoa et Toliara.","mg":"Mandrakotra an''Antananarivo, Toamasina, Antsirabe, Mahajanga, Fianarantsoa ary Toliara izao ny mpamonjy voina mpilatsaka an-tsitrapo."}'::jsonb,
  '{"en":"# Care is Resistance\n\nThe medic network has grown to **86 trained volunteers** working in 6 cities. Each team carries:\n\n- Tear gas exposure kits (saline, water, eye protection)\n- Trauma bandages and tourniquet\n- Mental health de-escalation cards\n- Charged backup phones with legal hotlines\n\nIf you have first-aid certification and want to join, sign up through the Field Academy module *Street First Aid*.","fr":"# Prendre soin, c''est résister\n\nLe réseau médic compte **86 bénévoles formés** dans 6 villes. Chaque équipe transporte :\n\n- Kits exposition gaz lacrymo (sérum, eau, protection oculaire)\n- Bandages traumato et garrot\n- Cartes de désescalade santé mentale\n- Téléphones de secours chargés\n\nSi vous avez une certification de premiers secours, inscrivez-vous via le module *Premiers secours de rue*.","mg":"# Fikarakarana dia fanoherana\n\nNihamaro ho **mpilatsaka an-tsitrapo voaofana 86** mandrakotra tanàna 6 ny tambazotra medic. Ny ekipa tsirairay dia mitondra:\n\n- Kit fiarovana amin''ny gaz lacrymo\n- Bandeau ho an''ny ratra sy tourniquet\n- Karatra fanampiana ara-tsaina\n- Finday tahiry voakaroka\n\nRaha manana fanamarinana fanampiana voalohany ianao, hisoratra anarana amin''ny modely *Fanampiana voalohany an-dalambe*."}'::jsonb,
  'manual', true, now() - interval '5 days')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.news (slug, title, excerpt, body, source, published, published_at) VALUES
('plan-action-2026',
  '{"en":"2026 Action Plan: Three Pillars","fr":"Plan d''action 2026 : trois piliers","mg":"Drafitr''asa 2026: andry telo"}'::jsonb,
  '{"en":"Education, civic monitoring, peaceful mobilization. The 2026 roadmap published with measurable goals.","fr":"Éducation, veille citoyenne, mobilisation pacifique. La feuille de route 2026 publiée avec des objectifs mesurables.","mg":"Fanabeazana, fanaraha-maso sivika, hetsika am-pilaminana. Navoaka ny drafitra 2026 misy tanjona azo refesina."}'::jsonb,
  '{"en":"# Where We Are Going\n\n**Pillar 1 — Education.** Train 2,000 youth in digital safety, organizing, and rights by end of 2026. Open a Field Academy node in every region.\n\n**Pillar 2 — Civic monitoring.** Deploy a citizen observation network for budget execution and public service delivery. Publish monthly briefs.\n\n**Pillar 3 — Peaceful mobilization.** Build a permanent legal aid fund, expand the medic network to 12 cities, and maintain a verified information channel countering disinformation.\n\nWe measure success in trained youth, supported legal cases, and verified public reports — not in followers.","fr":"# Où nous allons\n\n**Pilier 1 — Éducation.** Former 2 000 jeunes à la sécurité numérique, à l''organisation et aux droits d''ici fin 2026. Ouvrir un nœud Académie dans chaque région.\n\n**Pilier 2 — Veille citoyenne.** Déployer un réseau d''observation pour l''exécution budgétaire et les services publics. Publier des notes mensuelles.\n\n**Pilier 3 — Mobilisation pacifique.** Constituer un fonds permanent d''aide juridique, étendre le réseau médic à 12 villes, et maintenir un canal d''information vérifiée.\n\nNous mesurons le succès en jeunes formés, dossiers soutenus, rapports vérifiés — pas en abonnés.","mg":"# Aiza isika no mizotra\n\n**Andry 1 — Fanabeazana.** Hampianatra tanora 2 000 momba ny fiarovana an-tserasera, ny fandaminana, sy ny zo amin''ny faran''ny 2026. Hisokatra Akademia isaky ny faritra.\n\n**Andry 2 — Fanaraha-maso sivika.** Hametraka tambazotra fanaraha-maso ho an''ny fampiharana ny tetibola sy ny serivisim-bahoaka.\n\n**Andry 3 — Hetsika am-pilaminana.** Hanangana tahirim-bola ara-dalàna maharitra, hampitatra ny tambazotra medic ho an''ny tanàna 12.\n\nMandrefy ny fahombiazana amin''ny tanora voaofana sy tatitra voamarina izahay — fa tsy amin''ny mpanaraka."}'::jsonb,
  'manual', true, now() - interval '7 days')
ON CONFLICT (slug) DO NOTHING;

-- Events
INSERT INTO public.events (slug, title, description, starts_at, ends_at, location, source, published, rsvp_enabled) VALUES
('formation-medic-toamasina',
  '{"en":"Medic Training — Toamasina","fr":"Formation médic — Toamasina","mg":"Fiofanana medic — Toamasina"}'::jsonb,
  '{"en":"One-day intensive: tear gas response, wound care, mental health de-escalation. Free, certification provided.","fr":"Journée intensive : réponse aux gaz lacrymo, soins des plaies, désescalade santé mentale. Gratuit, certification fournie.","mg":"Fiofanana iray andro: fiatrehana ny gaz lacrymo, fikarakarana ratra. Maimaim-poana, misy fanamarinana."}'::jsonb,
  now() + interval '14 days', now() + interval '14 days' + interval '8 hours',
  'Toamasina — Centre Communautaire', 'manual', true, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.events (slug, title, description, starts_at, ends_at, location, source, published, rsvp_enabled) VALUES
('atelier-securite-numerique-tana',
  '{"en":"Digital Safety Workshop — Antananarivo","fr":"Atelier sécurité numérique — Antananarivo","mg":"Atrikasa fiarovana an-tserasera — Antananarivo"}'::jsonb,
  '{"en":"Hands-on: encrypted messaging, account hardening, phone seizure protocols. Bring your device.","fr":"Pratique : messagerie chiffrée, sécurisation des comptes, protocole en cas de saisie du téléphone. Apportez votre appareil.","mg":"Fanazaran-tena: hafatra voabolisy, fiarovana kaonty, protokoly raha alaina ny finday. Ento ny fitaovanao."}'::jsonb,
  now() + interval '21 days', now() + interval '21 days' + interval '4 hours',
  'Antananarivo — Hub Innovation', 'manual', true, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.events (slug, title, description, starts_at, ends_at, location, source, published, rsvp_enabled) VALUES
('table-ronde-fianarantsoa',
  '{"en":"Civic Roundtable — Fianarantsoa","fr":"Table ronde citoyenne — Fianarantsoa","mg":"Latabatra boribory sivika — Fianarantsoa"}'::jsonb,
  '{"en":"Open dialogue with local civil society on transparency, youth participation, and peaceful organizing.","fr":"Dialogue ouvert avec la société civile locale sur la transparence, la participation des jeunes et l''organisation pacifique.","mg":"Ifanakalozan-kevitra misokatra miaraka amin''ny fiarahamonim-pirenena momba ny mangarahara sy ny fandraisan''ny tanora anjara."}'::jsonb,
  now() + interval '28 days', now() + interval '28 days' + interval '3 hours',
  'Fianarantsoa — Salle Tranompokonolona', 'manual', true, true)
ON CONFLICT (slug) DO NOTHING;

-- Resources
INSERT INTO public.resources (slug, title, summary, body, category, read_minutes, source, published) VALUES
('gestion-stress-manifestation',
  '{"en":"Managing Stress in High-Pressure Mobilization","fr":"Gérer le stress en mobilisation sous pression","mg":"Fitantanana ny adin-tsaina amin''ny hetsika sarotra"}'::jsonb,
  '{"en":"Practical breathing, grounding, and team-care techniques for marshals and participants.","fr":"Techniques pratiques de respiration, ancrage et soutien collectif pour marshals et participants.","mg":"Fomba fiainana sy fanampiana ho an''ny mpitarika sy mpandray anjara."}'::jsonb,
  '{"en":"# Stay Steady\n\nFear is information, not weakness. Use these tools:\n\n## 4-7-8 Breathing\nInhale 4s, hold 7s, exhale 8s. Repeat 4 cycles. Lowers heart rate within 90 seconds.\n\n## 5-4-3-2-1 Grounding\nName 5 things you see, 4 you touch, 3 you hear, 2 you smell, 1 you taste. Pulls you out of panic spirals.\n\n## Buddy Check-In\nEvery 30 minutes, look your buddy in the eye and ask: ''Body okay? Mind okay?'' Two questions, two honest answers.\n\n## After-Action Care\nDecompress within 24h. Hot shower, full meal, 8h sleep. Skip social media for 12h. Call the mental health hotline if intrusive thoughts persist.","fr":"# Restez ancré\n\nLa peur est une information, pas une faiblesse.\n\n## Respiration 4-7-8\nInspirez 4s, retenez 7s, expirez 8s. 4 cycles. Baisse le rythme cardiaque en 90 secondes.\n\n## Ancrage 5-4-3-2-1\n5 choses vues, 4 touchées, 3 entendues, 2 senties, 1 goûtée. Sort des spirales de panique.\n\n## Check-in binôme\nToutes les 30 min, regardez votre binôme dans les yeux : ''Corps ok ? Esprit ok ?''\n\n## Soin après action\nDécompresser dans les 24h. Douche chaude, repas complet, 8h de sommeil. Pas de réseaux sociaux pendant 12h.","mg":"# Mijoroa tsara\n\nNy tahotra dia vaovao, fa tsy fahalemena.\n\n## Fiainana 4-7-8\nMiaina 4s, tazony 7s, mivoaka 8s. Avereno indroa efatra.\n\n## Fametrahana 5-4-3-2-1\nLazao 5 hitanao, 4 tsapainao, 3 renao, 2 fofony, 1 tsapainao am-bava.\n\n## Fanamarinana ny mpiara-miasa\nIsaky ny 30 minitra, lazao: ''Tsara ny vatana? Tsara ny saina?''\n\n## Fikarakarana aorian''ny hetsika\nMandroa mafana, mihinana feno, matory 8 ora. Ialao ny tambajotra serasera mandritra ny 12 ora."}'::jsonb,
  'street_safety', 6, 'manual', true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.resources (slug, title, summary, body, category, read_minutes, source, published) VALUES
('communication-chiffree',
  '{"en":"Encrypted Communication Basics","fr":"Bases de la communication chiffrée","mg":"Fototry ny fifandraisana voabolisy"}'::jsonb,
  '{"en":"Choose the right tool, configure it correctly, and avoid common metadata leaks.","fr":"Choisir le bon outil, le configurer correctement, éviter les fuites de métadonnées.","mg":"Mifidiana fitaovana, alamino tsara, ialao ny famoahana metadata."}'::jsonb,
  '{"en":"# Encrypt by Default\n\n## Tool Choice\n- **Signal** — best general-purpose end-to-end encrypted messenger. Verified by independent audits.\n- **Element / Matrix** — for federated group coordination, self-hostable.\n- **Briar** — works without internet, peer-to-peer over Bluetooth/WiFi. Ideal when networks are throttled.\n\n## Critical Settings\n1. Enable **disappearing messages** (24h–7d depending on sensitivity)\n2. Verify **safety numbers** with key contacts in person\n3. Disable **message previews** on lock screen\n4. Set a strong **app PIN** separate from your phone unlock\n\n## Metadata Leaks to Avoid\n- Group names that reveal purpose — use neutral codes\n- Profile photos showing faces or locations\n- Linking your real phone number — use a secondary SIM if possible\n- Cloud backups (iCloud, Google Drive) — they break end-to-end encryption","fr":"# Chiffrez par défaut\n\n## Choix d''outil\n- **Signal** — meilleur messager E2E généraliste, audité.\n- **Element / Matrix** — coordination de groupe fédérée.\n- **Briar** — fonctionne sans internet, en P2P. Idéal en cas de bridage réseau.\n\n## Paramètres critiques\n1. Activez les **messages éphémères** (24h–7j)\n2. Vérifiez les **numéros de sécurité** en personne\n3. Désactivez les **aperçus** sur l''écran verrouillé\n4. Définissez un **code PIN d''application** distinct\n\n## Fuites à éviter\n- Noms de groupe révélateurs — utilisez des codes neutres\n- Photos de profil avec visages\n- Numéro réel — privilégiez une SIM secondaire\n- Sauvegardes cloud — elles cassent le chiffrement E2E","mg":"# Voabolisy hatrany\n\n## Safidio ny fitaovana\n- **Signal** — tsara indrindra ho an''ny fifandraisana voabolisy.\n- **Element / Matrix** — fandrindrana vondrona.\n- **Briar** — miasa tsy misy internet.\n\n## Lamina manan-danja\n1. Aelao ny **hafatra mandalo** (24 ora–7 andro)\n2. Hamarino ny **isa fiarovana** mifanatrika\n3. Vonoy ny **topimaso** amin''ny écran mihidy\n4. Mametraka **PIN** hafa\n\n## Famoahana hialana\n- Anaran''ny vondrona miharihary\n- Sary misy tarehy\n- Laharana finday tena — ampiasao SIM hafa\n- Tahiry cloud — manimba ny E2E"}'::jsonb,
  'digital_safety', 7, 'manual', true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.resources (slug, title, summary, body, category, read_minutes, source, published) VALUES
('securite-comptes-sociaux',
  '{"en":"Hardening Your Social Media Accounts","fr":"Sécuriser vos comptes de réseaux sociaux","mg":"Fiarovana ny kaonty serasera"}'::jsonb,
  '{"en":"Two-factor authentication, login alerts, session reviews, and what to do after a takeover attempt.","fr":"Double authentification, alertes de connexion, révision des sessions, et que faire après une tentative de piratage.","mg":"Fanamarinana roa, fampahafantarana fidirana, fanaraha-maso ny session, ary inona no atao raha misy fakana."}'::jsonb,
  '{"en":"# Lock Your Accounts\n\n## Step 1: Strong, Unique Passwords\nUse a password manager (Bitwarden is free and audited). Each account gets a 20+ character random password. Never reuse.\n\n## Step 2: 2FA — But Not SMS\nSMS 2FA can be bypassed via SIM swap. Use:\n- **Authenticator app** (Aegis on Android, Raivo on iOS)\n- **Hardware key** (YubiKey) for highest-risk accounts\n\n## Step 3: Audit Sessions Weekly\nEvery social platform shows active sessions. Log out anything unfamiliar. Change password immediately if you see a foreign device.\n\n## Step 4: Backup Codes\nGenerate and store backup 2FA codes offline (paper, encrypted USB). Without them, you can be locked out permanently.\n\n## Step 5: After a Takeover Attempt\n1. Change password from a clean device\n2. Revoke all sessions\n3. Rotate 2FA secrets\n4. Notify your network so impersonation attempts are caught\n5. Document the incident (screenshots, timestamps) for the legal team","fr":"# Verrouillez vos comptes\n\n## 1. Mots de passe forts et uniques\nUtilisez un gestionnaire (Bitwarden, gratuit et audité). 20+ caractères aléatoires par compte.\n\n## 2. 2FA — mais pas SMS\nLe SMS peut être contourné par SIM swap. Utilisez :\n- **App d''authentification** (Aegis, Raivo)\n- **Clé physique** (YubiKey) pour les comptes critiques\n\n## 3. Audit hebdomadaire des sessions\nDéconnectez tout appareil inconnu, changez le mot de passe immédiatement.\n\n## 4. Codes de secours\nGénérez et stockez hors-ligne (papier, USB chiffré).\n\n## 5. Après une tentative de piratage\n1. Changer le mot de passe depuis un appareil propre\n2. Révoquer toutes les sessions\n3. Régénérer les secrets 2FA\n4. Prévenir votre réseau\n5. Documenter (captures, horodatages)","mg":"# Hidio ny kaonty\n\n## 1. Tenimiafina matanjaka\nAmpiasao Bitwarden. Litera 20+ kisendrasendra.\n\n## 2. 2FA — fa tsy SMS\nMety ho takiana ny SMS. Ampiasao:\n- **App authentificateur** (Aegis, Raivo)\n- **Lakile fitaovana** (YubiKey)\n\n## 3. Fanaraha-maso isan-kerinandro\nVoaroahy ny fitaovana tsy fantatra.\n\n## 4. Kaody tahiry\nAtaovy an-taratasy na USB voabolisy.\n\n## 5. Aorian''ny andrana fakana\n1. Ovay ny tenimiafina amin''ny fitaovana madio\n2. Foano ny session rehetra\n3. Avereno ny 2FA\n4. Ampandreneso ny tambajotra\n5. Soraty ny zava-niseho"}'::jsonb,
  'digital_safety', 8, 'manual', true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.resources (slug, title, summary, body, category, read_minutes, source, published) VALUES
('observation-citoyenne-urnes',
  '{"en":"Citizen Election Observation","fr":"Observation citoyenne des urnes","mg":"Fanaraha-maso ny latsa-bato"}'::jsonb,
  '{"en":"How to observe a polling station legally, document irregularities, and submit verified reports.","fr":"Comment observer un bureau de vote légalement, documenter les irrégularités, et transmettre des rapports vérifiés.","mg":"Ahoana no fanarahana ny biraom-pifidianana, fanoratana ny tsy fetezana, sy fandefasana tatitra."}'::jsonb,
  '{"en":"# Watch the Vote\n\n## Before Election Day\n- Register as an observer with an accredited civil society organization\n- Carry your accreditation badge AND national ID\n- Memorize the legal hotline number\n- Know what is and is not allowed (no campaigning, no influencing voters)\n\n## At the Polling Station\n- **Arrive at opening** to verify ballot box is empty and sealed\n- Note the exact opening time, number of registered voters, and station officials present\n- Observe — do not interfere. Stand in the designated observer area.\n- If you witness an irregularity: write it down with **time, place, names of officials, and exact description**. Photo only if explicitly permitted.\n\n## Closing and Counting\n- Stay until the official count is finished\n- Note the count totals and demand a copy of the official tally sheet (PV)\n- Cross-check the PV against the totals you observed\n\n## Reporting\nSubmit a structured report within 24h: location, observer name, witnessed facts (with timestamps), supporting evidence. Avoid speculation. The legal team will aggregate and act.","fr":"# Surveiller le scrutin\n\n## Avant le jour J\n- Accréditez-vous via une OSC reconnue\n- Portez badge ET pièce d''identité\n- Mémorisez la hotline juridique\n- Connaissez les règles (interdit de faire campagne)\n\n## Au bureau de vote\n- **Arrivée à l''ouverture** : urne vide et scellée\n- Notez heure, électeurs inscrits, agents présents\n- Observez sans interférer\n- Irrégularité : notez **heure, lieu, noms, description exacte**. Photo uniquement si autorisée.\n\n## Clôture et dépouillement\n- Restez jusqu''au comptage final\n- Notez les résultats et demandez le PV\n- Recoupez avec ce que vous avez observé\n\n## Rapport\nSous 24h : lieu, observateur, faits horodatés, preuves. Pas de spéculation.","mg":"# Aoka horaisina an-tanana ny latsa-bato\n\n## Mialoha ny andro fifidianana\n- Misorato amin''ny fikambanana ekena\n- Mitondrà kara-panondro sy badge\n- Tadidio ny laharana ara-dalàna\n- Fantaro ny fitsipika\n\n## Eny amin''ny biraom-pifidianana\n- **Tongava amin''ny fanokafana**: hamarino fa foana ny vatam-pifidianana\n- Soraty ny ora, isan''ny mpifidy, sy ny mpiandraikitra\n- Mijere fa aza miditra an-tsehatra\n- Tsy fetezana: soraty ny **ora, toerana, anarana, fanazavana**\n\n## Famaranana sy fanisana\n- Mijanona mandra-pahavitan''ny fanisana\n- Soraty ny vokatra ary angataho ny PV\n\n## Tatitra\nLefaso ao anatin''ny 24 ora: toerana, anarana, zava-misy voasoratra, porofo."}'::jsonb,
  'know_your_rights', 9, 'manual', true)
ON CONFLICT (slug) DO NOTHING;

-- Refresh notification banner
UPDATE public.notifications SET active = false WHERE active = true;
INSERT INTO public.notifications (title, body, level, active) VALUES
  ('{"en":"Q1 Transparency Report Published","fr":"Rapport de transparence T1 publié","mg":"Navoaka ny tatitra mangarahara Q1"}'::jsonb,
   '{"en":"Read the full breakdown of donations and allocations.","fr":"Consultez le détail complet des dons et allocations.","mg":"Vakio ny tatitra feno momba ny fanomezana sy fizarana."}'::jsonb,
   'info', true);
